name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make
      
    - name: Build
      run: make ttcpad
      
    - name: Process font
      run: ./ttcpad font.ttf

    - uses: actions/upload-artifact@v3
      with:
        name: font1.ttf
        path: ${{ github.workspace }}
    
    - uses: actions/upload-artifact@v3
      with:
        name: ttcpad
        path: ${{ github.workspace }}
