name: Unite Fonts

on: workflow_dispatch


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Unite
      run: .\ttf2ttc\UniteTTC.exe 222.ttc time2.ttf

    - uses: actions/upload-artifact@v3
      with:
        name: 222.ttc

        path: ${{ github.workspace }}
